---
version: '3'
services:
  little-link:
    image: ghcr.io/techno-tim/littlelink-server:latest
    container_name: littlelink-server
    environment:
      - META_TITLE=Frankie Freedom
      - META_DESCRIPTION=Frankie Freedom Link page
      - META_AUTHOR=Frankie Freedom
      - THEME=Dark
      - FAVICON_URL=https://pbs.twimg.com/profile_images/1138212736054075396/6-F30d-X_200x200.jpg
      - AVATAR_URL=https://pbs.twimg.com/profile_images/1138212736054075396/6-F30d-X_200x200.jpg
      - AVATAR_2X_URL=https://pbs.twimg.com/profile_images/1138212736054075396/6-F30d-X_400x400.jpg
      - AVATAR_ALT=Frankie Freedom Profile Pic
      - NAME=Frankie Freedom
      - BIO=Connect With Me!
      - GITHUB=https://github.com/Frankie-Freedom
      - TWITTER=https://twitter.com/frankie_freedom
      - INSTAGRAM=https://www.instagram.com/frankie_freedom
      - YOUTUBE=https://www.youtube.com/channel/UClZDE43KP-OomnkNYUcMG2Q
      - TWITCH=https://www.twitch.tv/mademperortyr/
      # - DISCORD=https://discord.gg/DJKexrJ
      # - TIKTOK=https://www.tiktok.com/@technotim
      # - KIT=https://kit.co/TechnoTim
      # - FACEBOOK=https://facebook.com
      # - FACEBOOK_MESSENGER=https://facebook.com
      # - LINKED_IN=https://linkedin.com
      # - PRODUCT_HUNT=https://www.producthunt.com/
      # - SNAPCHAT=https://www.snapchat.com/
      # - SPOTIFY=https://www.spotify.com/
      # - REDDIT=https://www.reddit.com/
      # - MEDIUM=https://medium.com
      # - PINTEREST=https://www.pinterest.com/
      # - EMAIL=you@example.com
      # - EMAIL_ALT=you@example.com
      # - SOUND_CLOUD=https://souncloud.com
      # - FIGMA=https://figma.com
      # - TELEGRAM=https://telegram.org/
      # - TUMBLR=https://www.tumblr.com/
      # - STEAM=https://steamcommunity.com/
      # - VIMEO=https://vimeo.com/
      # - WORDPRESS=https://wordpress.com/
      # - GOODREADS=https://www.goodreads.com/
      # - SKOOB=https://www.skoob.com.br/
      - FOOTER=Thanks for stopping by!
    ports:
      - 8080:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
